NUMBER_OF_ALLELES = 100
NUMBER_OF_PHYSICAL_GENES = 7
NUMBER_OF_ANIMALS = 100
NUMBER_OF_SPECIES = 3
NUMBER_OF_GENERATIONS = 5
GENERATION_DURATION = 3

STARTING_PLANTS = 1000

STARTING_INSECTS = 1000

STARTING_FISH = 1000
